name: Build and Publish Docker Image
on:
  pull_request:
    branches:
      - master
    paths:
      - Java/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x Java/gradlew

      - name: Going to Java directory
        run: cd ./Java

      - name: Run Gradle Tests
        run: ./gradlew test