name: Build and Publish Docker Image
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - Java/**
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x Java/gradlew

      - name: Run Gradle Tests
        working-directory: ./Java
        run: ./gradlew test

      - name: Build Java Application
        working-directory: ./Java
        run: ./gradlew build

      - name: Login to ghcr.io Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/crazyscreamx/pongshots:latest -t ghcr.io/crazyscreamx/pongshots:${GITHUB_SHA::7} .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/crazyscreamx/pongshots:latest
          docker push ghcr.io/crazyscreamx/pongshots:${GITHUB_SHA::7}