name: Test Java Application
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check for Java changes
        id: check-changes
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q '^Java/'; then
            echo "java-changed=true" >> $GITHUB_OUTPUT
          else
            echo "java-changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Skip tests if no Java changes
        if: steps.check-changes.outputs.java-changed == 'false'
        run: |
          echo "No Java code changes detected. Skipping tests."
          exit 0

      - name: Make gradlew executable
        if: steps.check-changes.outputs.java-changed == 'true'
        run: chmod +x Java/gradlew

      - name: Run Gradle Tests
        if: steps.check-changes.outputs.java-changed == 'true'
        working-directory: ./Java
        run: ./gradlew test